name: Scrape and Update Data

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Ensures GitHub credentials persist

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas openpyxl

      - name: Run Scraper.py
        run: python Scraper.py  # Ensure your script is named "Scraper.py"

      - name: Commit and push if changes exist
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add products.xlsx
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated products.xlsx with new data"
          git push
